name: 'load-dotenv'
description:
  'Load key value pairs from a .env file and set them as environment variables
  with optional masking'
author: 'Sergei Ryabkov'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  filePath:
    description: 'Full path to the .env file'
    required: true
  mask:
    description: 'Mask the values of environment variables'
    required: false
    default: 'false'

runs:
  using: node20
  main: dist/index.js
