name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Show Environment Variables Before
        run: |
          env | sort | grep VALUE
          env | sort | grep SECRET

      - name: Test Local Action (Values, Not Masked)
        id: test-action-values
        uses: ./
        with:
          dotEnvFilePath: ./__tests__/fixtures/test_values.env

      - name: Test Local Action (Secrets, Masked)
        id: test-action-secrets
        uses: ./
        with:
          dotEnvFilePath: ./__tests__/fixtures/test_secrets.env
          maskValues: true

      - name: Show Environment Variables After
        env:
          VALUE_10: ${{ env.VALUE_10 }}
          VALUE_11: ${{ env.VALUE_11 }}
          VALUE_12: ${{ env.VALUE_12 }}
          VALUE_20: ${{ env.VALUE_20 }}
          VALUE_21: ${{ env.VALUE_21 }}
          VALUE_22: ${{ env.VALUE_22 }}
          SECRET_10: ${{ env.SECRET_10 }}
          SECRET_11: ${{ env.SECRET_11 }}
          SECRET_12: ${{ env.SECRET_12 }}
          SECRET_20: ${{ env.SECRET_20 }}
          SECRET_21: ${{ env.SECRET_21 }}
          SECRET_22: ${{ env.SECRET_22 }}
        run: |
          env | sort | grep VALUE
          env | sort | grep SECRET
          echo "---"
          echo $VALUE_10
          echo $VALUE_11
          echo $VALUE_12
          echo $VALUE_20
          echo $VALUE_21
          echo $VALUE_22
          echo $SECRET_10 | sed 's/./& /g'
          echo $SECRET_11 | sed 's/./& /g'
          echo $SECRET_12 | sed 's/./& /g'
          echo $SECRET_20 | sed 's/./& /g'
          echo $SECRET_21 | sed 's/./& /g'
          echo $SECRET_22 | sed 's/./& /g'
